baseurl = "https://quentin.neyrat.io"
title = "~qneyrat"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

favicon_32 = "images/favicon-32x32.png"
favicon_16 = "images/favicon-16x16.png"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Quentin Neyrat"
    keywords = "blog,developer,personal"
    info = "Software engineer from Paris, France"
    avatarurl = "images/profile.jpg"

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = true

    rtl = false

    inverted = false
    custom_css = []

    googleAnalytics = "UA-109845043-1"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/qneyrat/"

[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/qneyrat/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/quentin-neyrat/"

[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

        [[languages.en.menu.main]]
        name = "Contact"
        weight = 3
        url = "/contact/"


    [languages.fr]
        languagename = "Français"

        [languages.fr.menu]

            [[languages.fr.menu.main]]
            name = "À Propos"
            weight = 1
            url = "/fr/a-propos/"

            [[languages.fr.menu.main]]
            name = "Articles"
            weight = 2
            url = "/fr/articles/"

            [[languages.fr.menu.main]]
            name = "Contact"
            weight = 3
            url = "/fr/contact/"
 